name: 'build-test'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - '*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          mainBranchName: 'master'
          releaseBranchPrfix: 'release'
          releaseBranchTaskPrefix: 'REL'